name: Deploy via ftp
on: push
jobs:
  deploy:
  - name: ftp-action
    runs-on: ubuntu-latest
    steps:
    - uses: sebastianpopp/ftp-action@v2.0.0
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist"
        remoteDir: "www"
        options: "--delete --asci"
